name: "Deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Zola"
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1

      - name: "Build"
        working-directory: ./site/
        run: zola build

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
